### ISSUE TITLE
Problems while run "paper_plots.jl"

### ISSUE THREAD

**Issue by emotionor** [louisponet/GdMn2O5_paper#1]
I was fortunate enough to read your article and wanted to download this code to rerun it. But I ran into some problems.
Currently 'using GdMn2O5' is working successfully on my machine. When I try to run the "paper_plots.jl", some errors and warnings occur. Could you help to deal with it as below?
'''
WARNING: redefinition of constant PATH_COLOR. This may fail, cause incorrect answers, or produce other errors.
ERROR: LoadError: TaskFailedException
Stacktrace:
 [1] wait
   @ .\task.jl:334 [inlined]
 [2] threading_run(func::Function)
   @ Base.Threads .\threadingconstructs.jl:38
 [3] macro expansion
   @ .\threadingconstructs.jl:97 [inlined]
 [4] neb_barrier_ledgers(sweep_ledgers::Vector{Ledger}, path_ranges::Vector{StepRange}, c::Int64, n_interpolations::Int64)
   @ GdMn2O5 $PATH\GdMn2O5_paper-main\GdMn2O5_paper\src\ledger.jl:429
 [5] energy_barriers(sweep_ledgers::Vector{Ledger}, start_H::Float64, stop_H::Float64, c::Int64, n_interpolations::Int64)
   @ GdMn2O5 $PATH\GdMn2O5_paper-main\GdMn2O5_paper\src\ledger.jl:466
 [6] top-level scope
   @ $PATH\GdMn2O5_paper-main\GdMn2O5_paper\scripts\paper_plots.jl:84

    nested task error: WARNING: both Plots and Glimpse export "Color"; uses of it in module GdMn2O5 must be qualified
WARNING: both Plots and FileIO export "Formatted"; uses of it in module GdMn2O5 must be qualified
WARNING: both Glimpse and Optim export "Sphere"; uses of it in module GdMn2O5 must be qualified
WARNING: both Plots and LinearAlgebra export "rotate!"; uses of it in module GdMn2O5 must be qualified
WARNING: both Glimpse and Unitful export "unit"; uses of it in module GdMn2O5 must be qualified
UndefVarError: set_angles! not defined
    Stacktrace:
     [1] neb(ledgers::Vector{Ledger}, c::Int64)
       @ GdMn2O5 $PATH\GdMn2O5_paper-main\GdMn2O5_paper\src\optimize.jl:135
     [2] macro expansion
       @ $PATH\GdMn2O5_paper-main\GdMn2O5_paper\src\ledger.jl:444 [inlined]
     [3] (::GdMn2O5.var"#140#threadsfor_fun#134"{Vector{Ledger}, Vector{StepRange}, Int64, Int64, Vector{Vector{Ledger}}, UnitRange{Int64}})(onethread::Bool)
       @ GdMn2O5 .\threadingconstructs.jl:85
     [4] (::GdMn2O5.var"#140#threadsfor_fun#134"{Vector{Ledger}, Vector{StepRange}, Int64, Int64, Vector{Vector{Ledger}}, UnitRange{Int64}})()
       @ GdMn2O5 .\threadingconstructs.jl:52
in expression starting at $PATH\GdMn2O5_paper-main\GdMn2O5_paper\scripts\paper_plots.jl:84
'''

**Comment by louisponet** [comment]
Hi,

Thank you for your interest. I've updated the file and repository, now it should be able to run (use latest master of Overseer). If you want to see specific plots, you can comment and uncomment certain parts of the paper_plots.jl script.

Let me know if that helped

Best,
Louis

**Comment by emotionor** [comment]
Thank you very much for your help! The updated script has run successfully and produced figures.
